"""Generate a zero-dependency JavaScript ES-module client (client.mjs)
from a discovered OpenAPI 3.1 spec.

The generated module exposes one async function per endpoint, plus a default
`createClient({ baseUrl, auth, fetch })` factory. It uses the global fetch API
and works in Node 18+, Deno, Bun, and modern browsers.
"""

from __future__ import annotations

import re
from pathlib import Path


def _safe_id(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_")
    if not cleaned:
        cleaned = "op"
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def _operation_function(
    method: str, path: str, op: dict
) -> tuple[str, str]:
    op_id = _safe_id(op.get("operationId") or f"{method}_{path}")
    summary = op.get("summary", "").replace("*/", "*\\/")

    path_params: list[str] = []
    query_params: list[str] = []
    header_params: list[str] = []
    for p in op.get("parameters", []) or []:
        name = _safe_id(p["name"])
        location = p.get("in")
        if location == "path":
            path_params.append(name)
        elif location == "query":
            query_params.append(name)
        elif location == "header":
            header_params.append((name, p["name"]))  # type: ignore[arg-type]

    has_body = bool(op.get("requestBody"))
    args = []
    if path_params:
        args.extend(path_params)
    options_props = ["query", "headers", "signal"]
    if has_body:
        options_props.insert(0, "body")
    args.append("{ " + ", ".join(options_props) + " } = {}")
    arg_str = ", ".join(args)

    # Build URL with path params interpolated
    url_expr = "`${baseUrl}" + path + "`"
    for name in path_params:
        url_expr = url_expr.replace(
            "{" + name + "}", "${encodeURIComponent(" + name + ")}"
        )

    body_lines = [f"  /** {summary} */" if summary else ""]
    body_lines.append(f"  async function {op_id}({arg_str}) {{")
    body_lines.append(f"    const url = new URL({url_expr});")
    if query_params:
        qnames = ", ".join(f'"{n}"' for n in query_params)
        body_lines.append(
            "    if (query) for (const k of Object.keys(query)) "
            "url.searchParams.set(k, query[k]);"
        )
        body_lines.append(
            f"    // Known query parameters: [{qnames}]"
        )
    body_lines.append("    const finalHeaders = { ...defaultHeaders };")
    body_lines.append("    if (headers) Object.assign(finalHeaders, headers);")
    if has_body:
        body_lines.append("    let payload = body;")
        body_lines.append(
            "    if (body && typeof body === 'object' && !(body instanceof FormData) "
            "&& !(body instanceof ArrayBuffer) && !(body instanceof Blob)) {"
        )
        body_lines.append("      payload = JSON.stringify(body);")
        body_lines.append(
            "      if (!finalHeaders['content-type'] && !finalHeaders['Content-Type'])"
        )
        body_lines.append(
            "        finalHeaders['content-type'] = 'application/json';"
        )
        body_lines.append("    }")
    body_lines.append("    const res = await fetchImpl(url, {")
    body_lines.append(f"      method: '{method.upper()}',")
    body_lines.append("      headers: finalHeaders,")
    if has_body:
        body_lines.append("      body: payload,")
    body_lines.append("      signal,")
    body_lines.append("    });")
    body_lines.append("    const ct = res.headers.get('content-type') || '';")
    body_lines.append(
        "    const data = ct.includes('application/json') ? await res.json() : await res.text();"
    )
    body_lines.append(
        "    if (!res.ok) throw Object.assign(new Error(`HTTP ${res.status}`), "
        "{ status: res.status, data });"
    )
    body_lines.append("    return data;")
    body_lines.append("  }")
    return op_id, "\n".join(filter(None, body_lines))


def generate_js_client(spec: dict) -> str:
    info = spec.get("info", {})
    servers = spec.get("servers", [])
    default_base = servers[0]["url"] if servers else ""
    paths = spec.get("paths", {})

    funcs: list[str] = []
    op_ids: list[str] = []
    for path, methods in paths.items():
        for method, op in methods.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete", "head"}:
                continue
            op_id, code = _operation_function(method, path, op)
            funcs.append(code)
            op_ids.append(op_id)

    header = (
        "/**\n"
        f" * {info.get('title', 'API Client')}\n"
        f" * {info.get('description', '')}\n"
        " *\n"
        " * Auto-generated by site2cli. Zero-dependency ES module.\n"
        " * Works in Node 18+, Deno, Bun, and modern browsers.\n"
        " */\n\n"
    )
    factory = (
        "export function createClient({ baseUrl = "
        f"{default_base!r}"
        ", auth, fetch: fetchOverride, headers: extraHeaders } = {}) {\n"
        "  const fetchImpl = fetchOverride || (typeof fetch !== 'undefined' ? fetch : null);\n"
        "  if (!fetchImpl) throw new Error('No fetch implementation available. "
        "Pass { fetch } or run on Node 18+.');\n"
        "  const defaultHeaders = { ...(extraHeaders || {}) };\n"
        "  if (auth) {\n"
        "    if (auth.bearer) defaultHeaders['authorization'] = `Bearer ${auth.bearer}`;\n"
        "    if (auth.apiKey) defaultHeaders['x-api-key'] = auth.apiKey;\n"
        "    if (auth.headers) Object.assign(defaultHeaders, auth.headers);\n"
        "  }\n\n"
        + "\n\n".join(funcs)
        + "\n\n  return { "
        + ", ".join(op_ids)
        + " };\n}\n\nexport default createClient;\n"
    )
    return header + factory


def save_js_client(code: str, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(code, encoding="utf-8")
    return output_path
